apiVersion: v1
kind: Secret
metadata:
  name: '{{ printf "%s-secret" (include "s-shop-system.fullname" .) }}'
type: Opaque
stringData:
  DB_USER: '{{ index .Values.services .Values.serviceName "secret" "user" | quote }}'
  DB_PASSWORD: '{{ index .Values.services .Values.serviceName "secret" "password" | quote }}'