{{- if .Values.traefik.basicAuth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.traefik.basicAuth.name }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  users: |
    {{ .Values.traefik.basicAuth.users }}
---
{{- end }}
{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-secret
  namespace: {{ $.Values.global.namespace }}
type: Opaque
stringData:
  DB_USER: {{ $.Values.global.db.user | quote }}
  DB_PASSWORD: {{ $.Values.global.db.password | quote }}
---
{{- end }}
{{- end }}
