server:
  grpc_port: 9000
  http_port: 8000
kafka:
  brokers: ["kafka:9092"]
  topic: "order.placed"
database:
  host: postgresql
  port: "5432"
  name: notification_service
  user: user
  password: password
