server:
  port: 8000
  grpc_port: 9000
kafka:
  brokers: ["kafka:9092"]
  topic: "user.created"
auth_service_url: "http://auth-service.s-shop-system.svc.cluster.local:8000"
database:
  host: postgresql
  port: "5432"
  name: user_service
  user: user
  password: password
  maxConnections: 100
  minConnection: 2
  maxConnectionLifetime: 60 # seconds
  maxConnectionIdleTime: 1 # minutes