apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "s-shop-system.fullname" . }}'
  namespace: s-shop-system
  labels:
    app: '{{ .Values.serviceName }}'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: '{{ .Values.serviceName }}'
  template:
    metadata:
      labels:
        app: '{{ .Values.serviceName }}'
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}'
        checksum/secret: '{{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}'
    spec:
      containers:
        - name: app
          image: romasmi/s-shop-system:latest
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: '{{ printf "%s-config" (include "s-shop-system.fullname" .) }}'
            - secretRef:
                name: '{{ printf "%s-secret" (include "s-shop-system.fullname" .) }}'

          ports:
            - name: web
              containerPort: 8000

          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 200m

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000