apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: s-shop-system
  labels:
    app: billing-service
    component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: billing-service
    component: api
  ports:
    - name: web
      port: 8000
      targetPort: web
    - name: grpc
      port: 9000
      targetPort: 9000
