apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: s-shop-system
data:
  DB_NAME: "notification_service"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: s-shop-system
type: Opaque
stringData:
  DB_USER: "user"
  DB_PASSWORD: "password"
