fullnameOverride: postgresql
auth:
  username: user
  password: password
  database: social_network
primary:
  persistence:
    enabled: false
  service:
    type: LoadBalancer

metrics:
  enabled: true
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
