services:
  user:
    db:
      host: postgres
      port: "5432"
      name: user_service
      max_connections: 100
      min_connection: 2
      max_connection_lifetime: 60 # seconds
      max_connection_idle_time: 1 # minutes
    secret:
      user: user
      password: password

  auth:
    db:
      host: postgres
      port: "5432"
      name: auth_service
    secret:
      user: user
      password: password